/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
import javax.swing.JOptionPane;
public class ActivityP extends javax.swing.JFrame {
static int opx = 1;
static int p1=0;
static int p2=0;
    /**
     * Creates new form ActivityP
     */
    public ActivityP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        lp1 = new javax.swing.JLabel();
        lp2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 53, 47, 45));

        b2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 53, 47, 45));

        b3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 53, 47, 45));

        b6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 138, 47, 45));

        b5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 138, 47, 45));

        b4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 138, 47, 45));

        b9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 229, 47, 45));

        b8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 229, 47, 45));

        b7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 229, 47, 45));

        lp1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lp1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        lp2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lp2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b1.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
            b1.setText("X");
            opx = 0;
            }
        }
    }                                  

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b2.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
            b2.setText("X");
            opx = 0;
            }
        }
    }                                  

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b3.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
            b3.setText("X");
            opx = 0;
            }
        }
    }                                  

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b4.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
            b4.setText("X");
            opx = 0;
            }
        }
    }                                  

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b5.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
            b5.setText("X");
            opx = 0;
            }
        }
    }                                  

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b6.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
            b6.setText("X");
            opx = 0;
            }
        }
    }                                  

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b7.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
            b7.setText("X");
            opx = 0;
            }
        }
    }                                  

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b8.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
            b8.setText("X");
            opx = 0; 
            }
        }
    }                                  

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {                                    
        
    }                                   

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {                                     
        lp1.setText("Player 1 : "+p1);
        lp2.setText("Player 2 : "+p2);
        if(b1.getText().equalsIgnoreCase("X") && b2.getText().equalsIgnoreCase("X") && b3.getText().equalsIgnoreCase("X")){
           JOptionPane.showMessageDialog(null, "Jogador 1 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p1++;
            
        }
        if(b1.getText().equalsIgnoreCase("O") && b2.getText().equalsIgnoreCase("O") && b3.getText().equalsIgnoreCase("O")){
           JOptionPane.showMessageDialog(null, "Jogador 2 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p2++;
            
        }
        if(b4.getText().equalsIgnoreCase("X") && b5.getText().equalsIgnoreCase("X") && b6.getText().equalsIgnoreCase("X")){
           JOptionPane.showMessageDialog(null, "Jogador 1 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p1++;
            
        }
        if(b4.getText().equalsIgnoreCase("O") && b5.getText().equalsIgnoreCase("O") && b6.getText().equalsIgnoreCase("O")){
           JOptionPane.showMessageDialog(null, "Jogador 2 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p2++;
            
        }
        if(b7.getText().equalsIgnoreCase("X") && b8.getText().equalsIgnoreCase("X") && b9.getText().equalsIgnoreCase("X")){
           JOptionPane.showMessageDialog(null, "Jogador 1 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p1++;
            
        }
        if(b7.getText().equalsIgnoreCase("O") && b8.getText().equalsIgnoreCase("O") && b9.getText().equalsIgnoreCase("O")){
           JOptionPane.showMessageDialog(null, "Jogador 2 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p2++;
            
        }
        if(b1.getText().equalsIgnoreCase("X") && b4.getText().equalsIgnoreCase("X") && b7.getText().equalsIgnoreCase("X")){
           JOptionPane.showMessageDialog(null, "Jogador 1 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p1++;
            
        }
        if(b1.getText().equalsIgnoreCase("O") && b4.getText().equalsIgnoreCase("O") && b7.getText().equalsIgnoreCase("O")){
           JOptionPane.showMessageDialog(null, "Jogador 2 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p2++;
            
        }
        if(b2.getText().equalsIgnoreCase("X") && b5.getText().equalsIgnoreCase("X") && b8.getText().equalsIgnoreCase("X")){
           JOptionPane.showMessageDialog(null, "Jogador 1 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p1++;
            
        }
        if(b2.getText().equalsIgnoreCase("O") && b5.getText().equalsIgnoreCase("O") && b8.getText().equalsIgnoreCase("O")){
           JOptionPane.showMessageDialog(null, "Jogador 2 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p2++;
            
        }
        if(b3.getText().equalsIgnoreCase("X") && b6.getText().equalsIgnoreCase("X") && b9.getText().equalsIgnoreCase("X")){
           JOptionPane.showMessageDialog(null, "Jogador 1 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p1++;
            
        }
        if(b3.getText().equalsIgnoreCase("O") && b6.getText().equalsIgnoreCase("O") && b9.getText().equalsIgnoreCase("O")){
           JOptionPane.showMessageDialog(null, "Jogador 2 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p2++;
            
        }
        if(b1.getText().equalsIgnoreCase("X") && b5.getText().equalsIgnoreCase("X") && b9.getText().equalsIgnoreCase("X")){
           JOptionPane.showMessageDialog(null, "Jogador 1 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p1++;
            
        }
        if(b1.getText().equalsIgnoreCase("O") && b5.getText().equalsIgnoreCase("O") && b9.getText().equalsIgnoreCase("O")){
           JOptionPane.showMessageDialog(null, "Jogador 2 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p2++;
            
        }
        if(b3.getText().equalsIgnoreCase("X") && b5.getText().equalsIgnoreCase("X") && b7.getText().equalsIgnoreCase("X")){
           JOptionPane.showMessageDialog(null, "Jogador 1 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p1++;
            
        }
        if(b3.getText().equalsIgnoreCase("O") && b5.getText().equalsIgnoreCase("O") && b7.getText().equalsIgnoreCase("O")){
           JOptionPane.showMessageDialog(null, "Jogador 2 Ganhou");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            p2++;
            
        }
        if(!b1.getText().equalsIgnoreCase("") && !b2.getText().equalsIgnoreCase("") && !b3.getText().equalsIgnoreCase("") && !b4.getText().equalsIgnoreCase("") && !b5.getText().equalsIgnoreCase("") && !b6.getText().equalsIgnoreCase("") && !b7.getText().equalsIgnoreCase("") && !b8.getText().equalsIgnoreCase("") && !b9.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(null, "Deu Velha");
            b1.setText("");
            b2.setText("");
            b3.setText("");
            b4.setText("");
            b5.setText("");
            b6.setText("");
            b7.setText("");
            b8.setText("");
            b9.setText("");
            
            
        }
        
    }                                    

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if(opx==0){
            b9.setText("O");
            opx = 1;
        }else{
            if(opx == 1){
                b9.setText("X");
                opx = 0;
            }
        }
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivityP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivityP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivityP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivityP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivityP().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lp1;
    private javax.swing.JLabel lp2;
    // End of variables declaration                   
}
